# Generated by Django 4.2.1 on 2024-03-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]

# python manage.py migrate

# python manage.py sqlmigrate women 0001    
# BEGIN;
# --
# -- Create model Women
# --
# CREATE TABLE "women_women" (
#     "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
#     "title" varchar(255) NOT NULL,
#     "content" text NOT NULL, 
#     "time_create" datetime NOT NULL, 
#     "time_update" datetime NOT NULL, 
#     "is_published" bool NOT NULL);
# COMMIT;